### ISSUE TITLE
Event_Portal Peer-Review Issue

### ISSUE THREAD

**Issue by anyars-encarta** [firepicaso/Event_Portal#2]
Nice work on the work you have done so far. Good presentation of code. <img src="https://media4.giphy.com/media/R6gvnAxj2ISzJdbA63/giphy-downsized-medium.gif"/>

However, I think you have to pay attention to your linters and make sure they all passing.

Happy coding!

**Comment by wacoo** [comment]
Amazing progress in such a short time. Here are the issues I have noticed:

- The second menu bar doesn't have the links.
- The javascript code is not added
- Much of the content is empty.
I know you are not done with the project, this is just a reminder.

**Comment by MustakimMasum** [comment]
thanks, for the feedback

**Comment by ishimwepati** [comment]
"Wow! Your capstone project is absolutely impressive. The level of thoughtfulness, innovation, and meticulous execution you've demonstrated is truly commendable. Your project not only addresses a significant problem but also provides a comprehensive and well-reasoned solution.
